package edu.indiana.dlib.amppd.model;

import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;


/**
 * BagContent contains information of a final output file generated by a step of a Galaxy workflow invocation.
 * BagContent is not persisted as it's a subset of the fields in WorkflowResult. 
 * @author yingfeng
 */
@Data
@EqualsAndHashCode
@ToString(callSuper=true, onlyExplicitlyIncluded=true)
public class BagContent {	    
	private Long resultId;		// the id in WorkflowResult
	private String submitter;
	private Date dateCreated;	// job start time
	private Date dateUpdated;	// job end time
	private String workflowId;
	private String invocationId;
	private String stepId;
	private String outputId;	
	private String workflowName;
	private String workflowStep; // same as tool_id
	private String toolInfo;	 
	private String outputName;
	private String outputType;
	private String outputUrl;	// not stored in WorkflowResult but generated as {baseUrl}/workflow-results/{id}/output for WorkflowResult
	// primaryfile ID and name are kept in PrimaryfileBag as they are the same for each BagContent within PrimaryfileBag
}
