package edu.indiana.dlib.amppd.model;

import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;


/**
 * BagContent contains information of a final output file generated by a step of a Galaxy workflow invocation.
 * BagContent is not persisted as it's a subset of the fields in DashboardResult. 
 * @author yingfeng
 */
@Data
@EqualsAndHashCode
@ToString(callSuper=true, onlyExplicitlyIncluded=true)
public class BagContent {	    
	private Long resultId;		// the id in DashboardResult
	private String submitter;
	private Date date;
	private String workflowId;
	private String invocationId;
	private String stepId;
	private String outputId;	
	private String workflowName;
	private String workflowStep; // same as tool_id
	private String toolInfo;	 
	private String outputFile;
	private String outputType;
	private String outputUrl;	// not stored in DashboardResult but generated as {baseUrl}/dashboard/{id}/output for Dashboard
	// primaryfile ID and name are kept in PrimaryfileBag as they are the same for each BagContent within PrimaryfileBag
}
