package edu.indiana.dlib.amppd.model;

import java.util.Date;

import edu.indiana.dlib.amppd.web.GalaxyJobState;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;


/**
 * BagOutput contains information of a final output file generated by a step of a Galaxy workflow invocation.
 * It's a subset of the fields of a row in DashboardResult table.
 * @author yingfeng
 *
 */
@Data
@EqualsAndHashCode
@ToString(callSuper=true, onlyExplicitlyIncluded=true)
public class BagOutput {	    
	private Long id;			// the id in DashboardResult
	private Long primaryfileId;
	private String submitter;
	private Date date;
	private String workflowId;
	private String invocationId;
	private String stepId;
	private String outputId;	
	private String workflowName;
	private String workflowStep;
	private String toolVersion;
	private String outputFile;
	private String outputType;
	private String outputPath;	// full absolute path of the output file
	private String outputLink;	// obscure symlink generated for the output file
	private String outputUrl;	// full download URL in Galaxy
}
