# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # specify the version you desire here
      - image: circleci/openjdk:11.0.2-jdk
        environment:
          AMPPD_DB_URL: jdbc:postgresql://localhost:5432/circle_test
          AMPPD_DB_DDL: create
          AMPPD_FILE_ROOT: ~/amppd/files/          
#          DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/amppd
#          DATABASE_USER: username
#          DATABASE_PASSWORD: password
#          POSTGRES_USER: username
#          POSTGRES_DB: password
      - image: circleci/postgres:latest

    working_directory: ~/amppd

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      # Download and cache dependencies
      - restore_cache:
          keys:
            - amppd-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - amppd-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: amppd-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test